

```{r}
# Upload packages
require(rgdal)
require(leaflet)
require(leaflet.extras)
require(dplyr)
require(readxl)
require(stringr)

```

```{r, fig.width=1000, fig.height=10}
# 2018 Philadelphia Marathon Route
# Upload polylines, polypoints, and polygons
# This data was created from http://geojson.io/#map=2/20.0/0.0. 
# Point and line data was traced from the 2018 Philadelphia marathon website, https://philadelphiamarathon.phila.gov/#/
route <- readOGR("marathon.geojson")
plot(route)
markers <- readOGR("newmarkers.geojson")
plot(markers)
hoods <- readOGR("Neighborhoods_Philadelphia.geojson")
plot(hoods)

vpi <- readOGR("Vacant_Block_Percent_Combined.geojson")
plot(vpi)


```

```{r}
# Copy code from Template
leaflet() %>%
  addProviderTiles(providers$OpenMapSurfer.Grayscale, options = providerTileOptions(noWrap = TRUE)) %>%
  # Basemaps
  addTiles(options = providerTileOptions(noWrap = TRUE), group = "Default") %>%
  addProviderTiles("Esri.WorldImagery", options = providerTileOptions(noWrap = TRUE), group = "Imagery") %>%
  addProviderTiles("Esri.WorldTopoMap", options = providerTileOptions(noWrap = TRUE), group = "Topo") %>%
  addProviderTiles("Esri.WorldTerrain", options = providerTileOptions(noWrap = TRUE), group = "Terrain") %>%
   # Layers control
  addLayersControl(
    baseGroups = c("Default", "Imagery", "Topo", "Terrain"),
    options = layersControlOptions(collapsed = FALSE)
  )

```

```{r, fig.width=1000, fig.height=10}
# Plot map 

# Add an if else statement to change colors
getColor <- function(markers) {
  sapply(markers$marker.symbol, function(marker.symbol) {
  if(marker.symbol %in% "Start") {
    "green"
  } else if(marker.symbol %in% "Finish") {
    "red"
  } else {
    "orange"
  } })
}

# Add icon
icons <- awesomeIcons(
  text = ~as.character(marker.symbol),
  markerColor = getColor(markers)
)

# Create Map
leaflet() %>%
# Add Philly 2018 Marathon Route
  addPolylines(data = route, color = "#000000", fillOpacity = 1, weight = 10) %>%
# Add Philly Neighborhoods
  addPolygons(data = hoods, color = "#1ab2ff", label = ~mapname, fillOpacity = 0.00, weight = 3, highlightOptions = highlightOptions(color = "red", bringToFront = TRUE)) %>%
# Add Philly 2018 Mile Markers
  addAwesomeMarkers(data = markers, icon = icons, options = "circles", label = ~as.character(marker.symbol)) %>%
# Basemaps
  addProviderTiles(providers$OpenMapSurfer.Grayscale, options = providerTileOptions(noWrap = TRUE)) %>%
  addTiles(options = providerTileOptions(noWrap = TRUE), group = "Default") %>%
  addProviderTiles("Esri.WorldImagery", options = providerTileOptions(noWrap = TRUE), group = "Imagery") %>%
  addProviderTiles("Esri.WorldTopoMap", options = providerTileOptions(noWrap = TRUE), group = "Topo") %>%
  addProviderTiles("Esri.WorldTerrain", options = providerTileOptions(noWrap = TRUE), group = "Terrain") %>%
# Layers control
  addLayersControl(
    baseGroups = c("Default", "Imagery", "Topo", "Terrain"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
 setView( lat = 39.980379,  lng= -75.165490, zoom = 12.1)


```

```{r, fig.width=1000, fig.height=10}
markers@data



```

